# Generated by Django 4.1.7 on 2023-03-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_clientitem_transportationcost_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagesinglecapacity',
            old_name='value',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='transportationcost',
            old_name='value',
            new_name='cost',
        ),
    ]
