# Generated by Django 4.1.7 on 2023-03-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_value_storagesinglecapacity_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItemPriceAndCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.item')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.storage')),
            ],
        ),
        migrations.DeleteModel(
            name='StorageSingleCapacity',
        ),
    ]
