# Generated by Django 4.1.7 on 2023-03-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_storageitempriceandcapacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagetotalcapacity',
            old_name='value',
            new_name='total_capacity',
        ),
    ]
